project:
  type: website
  output-dir: docs

website:
  title: "Garen Avanesian"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Research
        href: research.qmd 
      - text: Talks
        href: talks.qmd
      - text: Publications
        href: my_publications.qmd
      - text: CV
        href: cv.qmd
      - text: Media
        href: media.qmd
    right:
      - icon: github
        href: https://github.com/karavan88
      - icon: linkedin
        href: https://www.linkedin.com/in/karavan88/
  

format:
  html:
    theme: cyborg
    css: 
      - styles.css
      - custom.css
    
    toc: false

editor: visual


