project:
  type: website
  output-dir: docs

website:
  title: "Garen Avanesian"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Projects
        menu:
        - text: Web Apps
          href: projects_web_apps.qmd
        - text: Econ Research
          href: projects_econ_research.qmd
        - text: Teaching
          href: projects_teaching.qmd
      - text: My Publications
        href: my_publications.qmd
      - text: Media
        href: media.qmd
    right:
      - icon: github
        href: https://github.com/karavan88
      - icon: linkedin
        href: https://www.linkedin.com/in/karavan88/
  

format:
  html:
    theme: cyborg
    css: 
      - styles.css
      - custom.css
    
    toc: false

editor: visual


